version: "3.1"

services:
  ldap:
    image: osixia/openldap:1.3.0
    ports:
      - 10389:389
    volumes:
      - .data/ldap:/var/lib/ldap
    environment:
      - LDAP_ADMIN_PASSWORD=admin

  keycloak:
    image: jboss/keycloak
    ports:
      - 8080:8080

    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
